# 配置项目启动端口号
server:
  port: 8080

# 配置数据源
spring:
  main:
    allow-circular-references: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zswwszd95
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8

  devtools:
    add-properties: true
    restart:
      additional-paths: src/main/java

# MyBatis配置（只能有一个mybatis:）
mybatis:
  # sql映射文件地址
  mapper-locations: classpath:mapper/*.xml
  # 别名
  type-aliases-package: cn.pxl.entity
  # 配置项
  configuration:
    default-statement-timeout: 30

# PageHelper配置
pagehelper:
  # 基础配置
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

  # 自动检测方言
  auto-dialect: true
  auto-runtime-dialect: true

# 日志配置
logging:
  level:
    cn.pxl.mapper: debug
    com.github.pagehelper: debug